name: Deploy to Pages

on:
  workflow_dispatch:
  push:
    branches: 
      - dev
    paths:
      - assets/comparison/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/configure-pages@v6

      - run: |
          mkdir .upload
          mv assets/ .upload/assets/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './upload'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
